export const musicArray=[
  {
    songItem:"Music/Music_1.mp3",
    songAlbum:'Music/Music_1.jpg',
  },
  {
    songItem:"Music/Music_2.mp3",
    songAlbum:'Music/Music_2.jpg',
  },
  {
    songItem:"Music/Music_3.mp3",
    songAlbum:'Music/Music_3.jpg',
  },
  {
    songItem:"Music/Music_4.mp3",
    songAlbum:'Music/Music_4.jpg',
  },
  {
    songItem:"Music/Music_5.mp3",
    songAlbum:'Music/Music_5.jpg',
  },
  {
    songItem:"Music/Music_6.mp3",
    songAlbum:'Music/Music_6.jpg',
  },
  {
    songItem:"Music/Music_7.mp3",
    songAlbum:'Music/Music_7.jpg',
  },
  {
    songItem:"Music/Music_8.mp3",
    songAlbum:'Music/Music_8.jpg',
  },
  {
    songItem:"Music/Music_9.mp3",
    songAlbum:'Music/Music_9.jpg',
  },
]